apiVersion: v1
kind: Service
metadata:
  name: health-care-service
spec:
  selector:
    app: health-care-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Make sure this matches the containerPort in your Deployment
  type: LoadBalancer
